import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const source = readFileSync(new URL('../server.js', import.meta.url), 'utf8');
const start = source.indexOf('const DEFAULT_SHOP_CATALOG = [');
const end = source.indexOf('let SHOP_CATALOG =', start);
assert(start >= 0 && end > start, 'shop catalog must be present');
const catalog = vm.runInNewContext(`${source.slice(start, end)}\nACTIVE_DEFAULT_SHOP_CATALOG`);
const byId = Object.fromEntries(catalog.map(item => [item.id, item]));

assert.equal(catalog.length, new Set(catalog.map(item => item.id)).size, 'item ids must be unique');
assert(catalog.every(item => Number.isFinite(item.cost) && item.cost > 0), 'every item needs a positive price');
assert(catalog.every(item => item.costType !== 'ai_personality' && item.costType !== 'canvas_tool'), 'retired products must not be sold');
assert.equal(byId.premium.cost, 500);
assert.equal(byId.neon_purple.cost, 20);
assert.equal(byId.happy_hour_sprint.durationMinutes, 10);
assert.equal(byId.happy_hour_marathon.durationMinutes, 60);
assert.equal(byId.slots_free_spin_single.spinCount, 1);
assert.equal(byId.vip_hour.durationMinutes, 60);
assert(catalog.filter(item => item.cost <= 50).length >= 20, 'the shop should offer plenty of affordable items');
const priceStart = source.indexOf('function shopBaseCostFor(');
const priceEnd = source.indexOf('function shopItemsFor(', priceStart);
const priceContext = { dailyLogins: {}, normalizeEmail: email => email, isPremiumEmail: email => email === 'premium@test.test' };
vm.createContext(priceContext);
vm.runInContext(source.slice(priceStart, priceEnd), priceContext);
assert.equal(priceContext.shopCostFor(byId.neon_purple, 'user@test.test'), 20);
assert.equal(priceContext.shopCostFor(byId.premium, 'user@test.test'), 500);
assert(priceContext.shopCostFor(byId.neon_purple, 'premium@test.test') < 20);
assert.equal(priceContext.shopCostFor(byId.streak_freeze, 'user@test.test'), 35);
priceContext.dailyLogins['user@test.test'] = { streakFreezes: 2 };
assert.equal(priceContext.shopCostFor(byId.streak_freeze, 'user@test.test'), 90);
console.log(`Shop catalog passed: ${catalog.length} items, ${catalog.filter(item => item.cost <= 50).length} at 50 coins or less.`);
