import assert from 'node:assert/strict';
import { guestPreview } from '../lib/guest_preview.js';
import { planOwnerAction } from '../lib/owner_account_tools.js';

const now = 1800000000000, secret = 'test-only-secret';
const trial = guestPreview('', secret, now);
assert.equal(trial.expiresAt, now + 60000);
assert.equal(guestPreview(trial.token, secret, now + 30000).expiresAt, trial.expiresAt, 'Refresh must not restart preview');
assert.ok(guestPreview(trial.token, secret, now + 61000).expiresAt < now + 61000, 'Expired preview stays expired');
assert.notEqual(guestPreview(trial.token.replace(/.$/, 'z'), secret, now + 10).token, trial.token, 'Tampered signatures rejected');
assert.doesNotThrow(() => guestPreview(`${now}.${'é'.repeat(64)}`, secret, now), 'Malformed cookie must not cause a server error');
const options = { owner: true, actor:'owner@example.test', passwords:{ 'a@example.test':'hash', 'b@example.test':'hash', 'owner@example.test':'hash' }, coins:{ 'a@example.test':123,'b@example.test':456 }, protectedEmail: email => email === 'owner@example.test' };
for (const action of ['reset-coins','remove-registrations']) assert.throws(()=>planOwnerAction({...options,owner:false,action}), e=>e.status===403);
assert.throws(()=>planOwnerAction({...options,action:'remove-registrations',emails:['owner@example.test'],confirmation:'REMOVE 1 REGISTRATIONS'}),e=>e.status===403);
assert.throws(()=>planOwnerAction({...options,action:'remove-registrations',emails:['missing@example.test'],confirmation:'REMOVE 1 REGISTRATIONS'}),e=>e.status===409);
assert.throws(()=>planOwnerAction({...options,action:'remove-registrations',emails:['a@example.test'],confirmation:'REMOVE 2 REGISTRATIONS'}),e=>e.status===400);
assert.throws(()=>planOwnerAction({...options,action:'reset-coins',confirmation:'yes'}),e=>e.status===400);
const removal = planOwnerAction({...options,action:'remove-registrations',emails:['a@example.test'],confirmation:'REMOVE 1 REGISTRATIONS'});
assert.deepEqual(removal.targets,['a@example.test']);
assert.ok(options.passwords['b@example.test'],'Deselected account preserved');
const reset = planOwnerAction({...options,action:'reset-coins',confirmation:'RESET ALL COINS'});
assert.deepEqual(reset.nextCoins,{'a@example.test':0,'b@example.test':0});
assert.equal(options.coins['a@example.test'],123,'Preview must not mutate balances');
console.log('Guest timing and owner account authorization tests passed.');
