[package]
name = "mitch-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mitch-server"
path = "src/main.rs"

[dependencies]
mitch-lib = { path = "../mitch-lib" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
regex = "1"
form_urlencoded = "1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"