name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Blue-Green Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Remote Blue-Green Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 38222
          script: |
            sudo /home/mitch/server/bun/tools/deploy.sh
